model:
  temp: temp

controller:
  objects:
    num_objects: 14
    spawn_mode: random #random, load
  max_iter: 5
  mode: search_for_grasp # search_for_grasp, search_and_grasp
  recognition: False
  realworld: False
  save_dir: objects_14
  load_states_dir: 'exp_results/objects_14/initial_scenarios'
    
epoch: 50
