model:
  temp: temp

controller:
  objects:
    num_objects: 4
    spawn_mode: random #random, load
  max_iter: 5
  mode: search_for_grasp # search_for_grasp, search_and_grasp
  recognition: False
  realworld: False
  save_dir: objects_4
  load_states_dir: 'exp_results/test/initial_scenarios_4'
    
epoch: 500
