model:
  temp: temp

controller:
  objects:
    num_objects: 8
    spawn_mode: random #random, load
  max_iter: 5
  mode: search_for_grasp # search_for_grasp, search_and_grasp
  recognition: False
  realworld: False
  save_dir: objects_8
  load_states_dir: 'exp_results/test/initial_scenarios_8'
    
epoch: 500
