model:
  temp: temp

controller:
  objects:
    num_objects: 8
    spawn_mode: load #random, load
    target: box
  grid_dim: SE2
  max_iter: 10
  mode: search_for_grasp # search_for_grasp, search_and_grasp
  action_pool: ['push', 'pick_and_place']
  recognition: False
  realworld: False
  save_dir: box_object_8
  load_states_dir: exp_results/box_object_8/initial_scenarios

enable_gui: False
run: epoch # epoch, idx
epoch: 50
idx : 2
