controller:
  objects:
    num_objects: 8
    spawn_mode: load # random, load
  max_iter: 10
  mode: search_and_grasp # search_for_grasp, search_and_grasp
  hinderance_score_weight: 0.1
  hinderance_mode: smooth
  action_pool: ["pick_and_place", "push"]
  recognition: True
  realworld: False
  save_dir: objects_2
  # load_states_dir: ../Search-for-Grasp_shared/exp_results/objects_8/initial_scenarios
  load_states_dir: exp_results/objects_2/initial_scenarios

idx : 2
