model:
  temp: temp

controller:
  objects:
    num_objects: 8
    spawn_mode: random #random, load
  max_iter: 10
  mode: search_for_grasp # search_for_grasp, search_and_grasp
  recognition: True
  realworld: False
  save_dir: objects_2
  load_states_dir: exp_results/objects_8/initial_scenarios

run: epoch # epoch, idx
epoch: 1
# idx : 2
