controller:
  objects:
    num_objects: 8
    spawn_mode: load
  max_iter: 10
  mode: search_for_grasp # search_for_grasp, search_and_grasp
  hinderance_score_weight: 0.1
  hinderance_mode: smooth
  action_pool: ["pick_and_place", "push"]
  recognition: True
  save_dir: exp_results_sim/objects_8
  load_states_dir: exp_configs/objects_8

idx : 3
